name: Публикация GitHub Pages

on:
  release:
    types: [published]
    branches:
      - webpack
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Получение исходников
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Установка зависимостей
        run: npm install --no-audit --no-fund

      - name: Сборка
        run: npm run build:single

      - name: Настройка Pages
        uses: actions/configure-pages@v5

      - name: Загрузка сайта
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Публикация
        id: deployment
        uses: actions/deploy-pages@v4